"=============================================================================
"
" NAME
"
"     .vimrc
"
" DESCRIPTION
"
"     Settings for Vim editor loaded upon startup.
"
" NOTES
"
"     UNIX, Mac OS X:  Copy to ~/.vimrc
"     Windows:         Copy to C:/Program Files/vim/_vimrc
"
" AUTHOR
"
"     Bram Moolenaar             <Bram@vim.org>
"     Sean Erik O'Connor         10 Oct 2024
"
"=============================================================================

set fileformat=unix
set encoding=UTF-8

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Vim can detect the file type.
filetype on

" Enable plugins
filetype plugin on

" Mouse and window behavior tuned for Microslime Windows.
behave mswin

" Restore Control-F to page forward instead of find dialog box.
"unmap<C-F>

" Allow backspacing over everything in insert mode.
set backspace=indent,eol,start

" Turn on backup option.
set backup

" Create the backup directory if it doesn't exist.
if !isdirectory($HOME.'/.vim/.backup')
    silent call mkdir( $HOME.'/.vim/.backup', 'p' )
endif

" Store backups in the home directory ~/.vim/.backup.
set backupdir=~/.vim/.backup

" Make a backup before overwriting the current buffer.
set writebackup

" Overwrite the original backup file.
set backupcopy=yes

" Put swap files in the home directory ~/.vim/.swp
if !isdirectory($HOME."/.vim/.swp")
    silent call mkdir( $HOME.'/.vim/.swp', 'p' )
endif

set directory=~/.vim/.swp

set history=2000     " Keep 2000 lines of command line history.
set ruler           " Show the cursor position all the time.
set showcmd         " Display incomplete commands.

set incsearch       " Do incremental searching.
set hlsearch        " Searches are highlighted.

set wildmenu        " File name completing using tabs cycles through all possibilities.
set wildmode=list:longest " Make similar to bash completion.
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pyc,*.xlsx:w  " Ignore these files when doing file name completion.

set lazyredraw      " Don't redraw screen while running macros.

set lines=80        " Number of lines visible on the screen.
set columns=160     " Number of columns visible on the screen.
winpos 700 100      " Initial window position (MacBookPro).
set winwidth=240    " Initial window width.
set winminwidth=150 " Minimum width.

set cursorline      " Highlight the current line.
set number          " Show line numbers.
set nosmartindent   " Don't use smart indenting.

set tabstop=4       " Tabs are 4 spaces wide.
set softtabstop=4   " When editing, tabs are 4 spaces wide.
set shiftwidth=4    " Indent 4 spaces.
set expandtab       " Expand tabs into spaces.
set smarttab        " tab in front of a line inserts shiftwidth spaces, and backspace will delete that many spaces.

set showmatch       " Show matching parentheses.
set matchtime=5     " Match time is 1/2 sec.

" Error blink and bell.
set errorbells
set visualbell

" Set file paths to my most commonly used directories (MacBookPro).
set path="~/Applications/vim/**"
set path+="~/Desktop/Sean/WebSite/**"

" Default directory is my current active subdirectory
" in my web page directory.
" This is where :e . takes us.
cd ~/Desktop/Sean/WebSite/Mathematics/AbstractAlgebra/PrimitivePolynomials/Project/SourceCode

" Set paths for tags files generated by Ctags.  See :help tags
" "./tags" means search for the file "tags" in the same directory as the current f i l e  you are editing.
" "tags" means search for the file "tags" in the current working directory (the directory shown by the command :pwd)
" NOTE:  this is affected if you set autochdir (see below).
" Then search from the directory containing tags to your home directory.
set tags=./tags,tags;~

" Automatically change the current working directory to the one containing the file which was opened.  See :help autochdir
"Note: When this option is on some plugins may not work.
set autochdir

" Color them the same as the C group-name "Type".
highlight link xType Type

" Persistent undo:  undo changes even after saving the file and exiting Vim.
if has('persistent_undo')
    set undofile
    set undodir=$HOME/.vim/.backup
endif

" ===============================================================================
" | Color scheme and font for the full gVim GUI.
" | Use the default for launching vim from a command window.
" ===============================================================================
if has("gui_running")

    colorscheme torte

    " To verify the if condition, on the Vim command line, do
    "    :echom has("x11")
    " and look for 1 or 0.
    "
    " To find out the font type:
    "     In the Vim command line, do
    "         :set guifont=*
    "     to make a menu come up.
    "
    "     Select the font from the menu.
    "
    "     Do the command
    "         :set guifont?
    "     to find out the name.
    "
    "     In the if tests below, add
    "         set guifont=<name of the font>
    "     Escape all spaces with backslashes.
    "
    if has("gui_win32")
        set guifont=Courier_New:h13:b
    " Test for Mac first.
    elseif has("mac")
        set guifont=Menlo\ Regular:h12
    " On Ubuntu Linux:
    elseif has("x11")
        set guifont=DejaVu\ Sans\ Mono\ 10
    " Otherwise
    else
        set guifont=*
    endif
endif

" Switch syntax highlighting on, when the terminal has colors.
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on     " Turn on syntax highlighting.
  set hlsearch  " Searches are highlighted.
endif

" ===============================================================================
" |  Abbreviations
" ===============================================================================

" Abbreviations.  My name:
:iabbrev soc Sean Erik O'Connor

" Right arrow.
:iabbrev rar &#10148;

:iabbrev bf \mathbf{
:iabbrev fb }

" ===============================================================================
" |  Shortcuts - HTML and CSS
" ===============================================================================

" Remapping looks like
"     <map_mode> <what you type> <what is executed>
" These are the map modes:
"     nnoremap - Map keys in normal mode.
"     inoremap - Map keys in insert mode.
"     vnoremap - Map keys in visual mode.

" Let comma be the character which starts any mapping command.
let mapleader=","

" Insert Blender hotkeys.
nnoremap ,bhot a <em class="hotkey"></em><ESC>4hi

" Insert html emphasis.
nnoremap ,em a <em></em><ESC>4hi

" Insert an HTML element with the indentation at the same level as the neighbors.
"     First CR finishes the call to function HTMLParagraph()
"     Second CR takes us out of command mode :
"     To see the echom debug statements, type :messages.  To clear all
"     messages type :messages clear
function! InsertHTMLElement( prefix, suffix )
    echom "HTMLParagraph"
    " Scan the previous few lines until you see a line which has an indent > 0.  
    " An indent value of -1 means the line does not exist (past the top or bottom of the file.  Zero means a blank line.
    let current_line_num = line(".")
    let num_lines_to_search = 10
    let previous_nonzero_indent = 0
    for line_num in range( current_line_num-1, current_line_num - num_lines_to_search, -1)
        echom 'line_num = ' line_num
        let line_indent = indent( line_num )
        echom 'line_indent = ' line_indent
        if line_indent > 0
            let previous_nonzero_indent = line_indent
            break
        endif
    endfor
    echom 'previous_nonzero_indent = ' previous_nonzero_indent
    "Create indentation with blanks.
    let blanks = repeat( " ", previous_nonzero_indent )
    echom 'blanks = ' '|' .. blanks .. '|'
    " Create  the HTML element in the form of a list.
    """""let HTMLElementLines = [ blanks .. '<div class="scrollBox"> <div class="scrollBoxContent">', blanks, blanks .. '</div></div>', '']
    let HTMLElementLines = [ blanks .. a:prefix, blanks, blanks .. a:suffix, '']
    echo 'HTMLElementLines = ' HTMLElementLines
    " Append the scroll box lines after the current line.
    call append( '.', HTMLElementLines )
endfunction

" The commands after the CR CR place the cursor into insert position.

" Insert a scroll box.
nnoremap <leader>sb :call InsertHTMLElement( '<div class="scrollBox"> <div class="scrollBoxContent">', '</div></div>' )<CR><CR>jjA

" Insert an html paragraph.
nnoremap <leader>par :call InsertHTMLElement( '<p>', '</p>' )<CR><CR>jjA

" Insert hyperlink.
nnoremap <leader>hr :call InsertHTMLElement('<a href="', '</a>')<CR><CR>kA<ESC>jj$JJa"><ESC>hhxi

" Insert an image.
nnoremap <leader>im :call InsertHTMLElement('<img class="centeredsmaller" alt="X" src="Images/X.jpg">','')<CR><CR>jfXfXxi

" Insert a mathematical thingies.
nnoremap <leader>def  :call InsertHTMLElement('<em>Definition</em>','')<CR><CR>jA  
nnoremap <leader>lem  :call InsertHTMLElement('<em>Lemma</em>','')<CR><CR>jA  
nnoremap <leader>prop :call InsertHTMLElement('<em>Proposition</em>','')<CR><CR>jA  
nnoremap <leader>th   :call InsertHTMLElement('<em>Theorem</em>','')<CR><CR>jA  
nnoremap <leader>pf   :call InsertHTMLElement('<em>Proof</em>','')<CR><CR>jA  
nnoremap <leader>cor  :call InsertHTMLElement('<em>Corrollary</em>','')<CR><CR>jA  
nnoremap <leader>qed  :call InsertHTMLElement('$\blacksquare$','')<CR><CR>jA  

" Insert a nonbreaking space.
nnoremap ,s i&nbsp;<ESC>

" ===============================================================================
" |  Shortcuts - miscellaneous
" ===============================================================================

" Make jk the same as ESCAPE in insert mode.
inoremap jk <esc>

" Reload this VIM resource file.
nnoremap ,sou :source $MYVIMRC<CR>

" Save the file.
nnoremap ,sa   :w<CR>

" ===============================================================================
" |  Shortcuts - formatting
" ===============================================================================

" Trim blanks at end of all lines. Turn off search highlighting.
nnoremap ,tbe :%s/\s*$//<CR><ESC>:nohlsearch<CR><ESC>

" Make p in Visual mode replace the selected text with the "" register.
vnoremap p <Esc>:let current_reg = @"<CR>gvs<C-R>=current_reg<CR><Esc>

" Turn off highlighting after searches.
nnoremap ,<SPACE> :nohlsearch<CR>

" Toggle comment lines.  You can highlight the range
" with the mouse and then type ,to
nnoremap ,to :call ToggleComment()<CR>

function! ToggleComment()
    " Get the line under the cursor
    " Check if it begins with |
    if getline(".") =~ '^|'
        let s:savedSearchPat=@/
        s/^|//
        let @/=s:savedSearchPat
    else
        let s:savedSearchPat=@/
        s/^/|/
        let @/=s:savedSearchPat
    endif
endfunction

" Convert C comments on a line to C++ comments.
nnoremap ,cc :call ConvertCCommentToCpp()<CR>

function! ConvertCCommentToCpp()
    " Get the line under the cursor
    " Check if contains a /*
    if getline(".") =~ '\/\*'
        let s:savedSearchPat=@/
        s/\/\*/\/\//
        let @/=s:savedSearchPat
    endif
    if getline(".") =~ '\*\/'
        let s:savedSearchPat=@/
        s/\*\///
        let @/=s:savedSearchPat
    endif
endfunction

" Justify a paragraph.
nnoremap ,j gqap

function! HardcopyPDF()
    " https://askubuntu.com/questions/705973/how-can-i-print-from-vim-to-pdf
    " Vim hardcopy generates a PostScript file.
    " Convert to PDF, delete the PS file, tell where the PDF is located.
    hardcopy > %.ps | !ps2pdf %.ps && rm %.ps && echom 'Created: %.pdf'
endfunction

" Hardcopy to *.pdf file.
nnoremap ,pdf :call HardcopyPDF()<CR>

" Special one time mapping.  Change master_xyz to local_xyz
nnoremap ,ll /master<CR>dt_ilocal<ESC>

" ===============================================================================
" |  Folding
" ===============================================================================
" zR - open all folds
" zM - close all folds
" zj, zk - move between folds
" za - toggle folds;  mapped to shortcut ,,
" :help usr_28
set foldmethod=indent  " Folding based on indentation.
set foldcolumn=2       " Show the status of the folds in the left column.
nnoremap <leader>, za

" Save the folds in this file upon write, and load again upon read.
" Saved in ~/.vim/view
augroup remember_folds
    autocmd! | " Clear all existing autocommands
    autocmd BufWinLeave * silent! mkview
    autocmd BufWinEnter * silent! loadview
augroup END
